name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:      
      - uses: ros-tooling/setup-ros@v0.6
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: mission_planner_srv
          target-ros2-distro: humble
          vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/humble/ros2.repos
